### ISSUE TITLE
When you share a picture, the anonymity dies

### ISSUE THREAD

**Issue by beeetooo** [wizeline/slack-stranger-bot#10]
![image](https://user-images.githubusercontent.com/13922607/32022189-3e103d7c-b99b-11e7-8194-7ff4c0982b4c.png)

I don't think this is a valid issue tho, because it might be something out of development control, but just wanted to point out this hahaha

**Comment by plutov** [comment]
Nice, thank you, will definitely have a look.

**Comment by plutov** [comment]
Hi @beeetooo , could you please check if it works for you now?
